baseURL = 'http://germ430.github.io/germ430public'
languageCode = 'en-us'
title = 'GERM 430: Der Holocaust | Winter 2022'
theme = 'digitalgarden'

[menu]
    [[menu.main]]
        name = 'Kurzplan'
        url = '/'
        weight = 1
    [[menu.main]]
        name = 'Werke'
        url = '/articles'
        weight = 2
    [[menu.main]]
        name = 'Abschluss Projekt'
        url = '/abschluss'
        weight = 3